"""Performing NLP using NLTK & scikit-learn."""

## TOKENIZATION ##

## PART OF SPEECH TAGGING ##

## REMOVING PUNCTUATION ##

## REMOVING STOPWORDS ##

## STEMMING / LEMMATIZATION ##

## FREQUENCY DISTRIBUTIONS ##

## COLLOCATIONS, BIGRAMS, TRIGRAMS ##

## CHUNKING ##

## SPLITTING TRAINING SETS & TEST SETS ##

## CLASSIFIERS & scikit-learn ##

## CROSS-VALIDATING CLASSIFIERS ##

## CREATING PIPELINES FOR CLASSIFIERS ##

